'use strict';
(() => {
const E=window.IRIS_V63,host=document.getElementById('irisRoot');if(!E||!host)return;
const COLORS=['#37c9ed','#49dda7','#c069ff','#ffbd56','#ed64c2','#8e94ff'];
const LABEL={IRIS:'IRIS',MINI3:'MINI‑3',MINI4:'MINI‑4'};
let data={series:[],evaluation:{}},draws=[],view='current',filter='all',page=0,scope='active',statsLimit=0,busy=false,message='Подключаю архив…',online=false,serverOnline=false,db=null,auto=true;
try{auto=localStorage.getItem('iris-v63-auto')!=='false';}catch{}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0'),money=n=>n===null||n===undefined?'сумма не определена':Number(n).toLocaleString('ru-RU')+' ₽';
const key='iris-v63',modeOptions=`<option value="all">Все режимы</option>${E.MODES.map(m=>`<option value="${m}">${LABEL[m]}</option>`).join('')}`;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('pozitron_iris_v63',1);r.onupgradeneeded=()=>r.result.createObjectStore('cache');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('Закройте старую вкладку Iris и обновите страницу'));});}
function cached(){return new Promise((resolve,reject)=>{const t=db.transaction('cache'),r=t.objectStore('cache').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
// Merge and save in a single transaction, including concurrent tabs. Show "saved" only on commit.
function commit(remote,generate){return new Promise((resolve,reject)=>{const t=db.transaction('cache','readwrite'),store=t.objectStore('cache'),r=store.get(key);let out;r.onsuccess=()=>{try{const previous=r.result||{series:[]};const map=new Map(previous.series.map(s=>[s.id,s]));for(const s of remote||[])map.set(s.id,s);out=E.process(draws,[...map.values()],new Date().toISOString(),{generate,origin:'local'});store.put({...out,draws:draws.slice(-800)},key);}catch(e){t.abort();reject(e);}};t.oncomplete=()=>resolve(out);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||new Error('Не удалось записать Iris'));});}
async function fetchJson(file){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch('./'+file+'?iris=010&t='+Date.now(),{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(timer);}}
async function refresh(generate=auto){if(busy)return;busy=true;render();try{const [h,a]=await Promise.allSettled([fetchJson('keno-history-v63.json'),fetchJson('iris-archive-v63.json')]);online=h.status==='fulfilled';serverOnline=a.status==='fulfilled'&&Array.isArray(a.value?.series);if(online){const fresh=E.normalize(h.value);if(!fresh.length)throw new Error('История тиражей пуста');if(!draws.length||fresh.at(-1).draw>=draws.at(-1).draw)draws=fresh;else online=false;}
if(!draws.length)throw new Error('Нет истории тиражей. Нажмите «Проверить» после восстановления связи.');const remote=serverOnline?a.value.series:[];
if(db){data=await commit(remote,Boolean(generate&&online));message=(online?'Автозапись сохранена':'Офлайн: проверены сохранённые факты')+(serverOnline?' · сервер подключён':' · серверный архив пока недоступен');}
else{data=E.process(draws,remote,new Date().toISOString(),{generate:false});message='Хранилище недоступно: только просмотр серверного архива. Новые местные серии не создаются.';}
}catch(e){message='Ошибка Iris: '+e.message;}finally{busy=false;render();}}
function balls(nums,hits=[],color){return `<div class="iris-balls">${nums.map(n=>`<span class="${hits.includes(n)?'hit':''}" ${color?`style="--series:${color}"`:''}>${pad(n)}</span>`).join('')}</div>`;}
function seriesColor(s){const serial=data.series.filter(x=>x.mode===s.mode).sort((a,b)=>a.sourceCutoff-b.sourceCutoff||a.id.localeCompare(b.id)).findIndex(x=>x.id===s.id);return COLORS[s.mode==='MINI3'?4:s.mode==='MINI4'?5:Math.max(0,serial)%4];}
function seriesCard(s,i,arch=false){const last=s.results.at(-1),color=seriesColor(s),best=s.results.length?Math.max(...s.results.map(r=>r.hitCount)):null,win=s.results.some(r=>r.payout>0),serial=data.series.filter(x=>x.mode===s.mode).sort((a,b)=>a.sourceCutoff-b.sourceCutoff||a.id.localeCompare(b.id)).findIndex(x=>x.id===s.id)+1;return `<article class="iris-series" style="--series:${color}"><div class="iris-series-head"><div><b>${LABEL[s.mode]} №${serial}</b> <span class="iris-pill">${s.status==='closed'?'Завершена':'Серия активна'}</span><small>${s.numbers.length} чисел · №${s.targetStart}–${s.targetEnd} · ${s.origin==='server'?'сервер':'это устройство'}</small></div><div class="iris-progress"><b>${s.results.length}/5</b><span aria-label="Проверено ${s.results.length} из 5">${Array.from({length:5},(_,j)=>`<i class="${s.results.some(r=>r.draw===s.targetStart+j)?'done':''}"></i>`).join('')}</span></div></div>${arch?'':balls(s.numbers,last?.hits||[],color)}<div class="iris-result"><span>${last?`Последний №${last.draw} · <b>${last.hitCount}/${s.numbers.length}</b>`:'Ожидает первого тиража'}</span><span>${last?.payout>0?'🔥 ':''}${last?money(last.payout):'—'}</span></div>${arch?`<div class="iris-note">Лучший: ${best??'—'}/${s.numbers.length} · ${win?'🔥 ':''}Сумма известных выплат: ${money(s.results.reduce((v,r)=>v+(r.payout||0),0))}${s.results.some(r=>r.payout===null)?' + нерассчитанные':''}</div>`:''}<details data-iris-detail="${esc(s.id)}"><summary>Открыть детали</summary>${arch?balls(s.numbers,[],color):''}<p class="iris-note">Фиксация: ${new Date(s.createdAt).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})} МСК<br>Источник: №${s.sourceCutoff} · A: ДА · версия ${esc(s.version)}</p>${s.results.map(r=>`<div class="iris-check"><b>№${r.draw} · ${esc(r.date)} ${esc(r.time)} · ${r.hitCount}/${s.numbers.length} ${r.payout>0?'🔥':''}</b><span>${money(r.payout)}</span><div class="iris-note">Совпали: ${r.hits.map(pad).join(' · ')||'нет'}</div>${balls(r.fact,r.hits)}</div>`).join('')||'<p class="iris-note">Результатов пока нет.</p>'}<p class="iris-note">Отбор v0.1: ${s.reason.map(x=>`${pad(x.n)} → ${esc(x.code)}`).join('; ')}. Ритм и связи на поле 10×8.</p>${s.conflicts?.length?`<p class="iris-error">Расхождение факта: №${s.conflicts.join(', ')}. Старую проверку не переписывали.</p>`:''}</details></article>`;}
function mapHtml(){const series=data.series.filter(s=>scope==='all'||s.status==='active');return `<section class="iris-box"><h3>Карта чисел 1–80</h3><select id="iris-map-scope"><option value="active" ${scope==='active'?'selected':''}>Все активные серии</option><option value="all" ${scope==='all'?'selected':''}>С учётом архива</option></select><div class="iris-grid">${Array.from({length:80},(_,i)=>{const list=series.filter(s=>s.numbers.includes(i+1)),cs=[...new Set(list.map(seriesColor))];return `<span class="${list.length?'used':''}" title="${esc(list.map(s=>`${LABEL[s.mode]}: №${s.targetStart}–${s.targetEnd}`).join('; '))}" ${cs.length?`style="background:linear-gradient(135deg,${cs.join(',')}${cs.length===1?','+cs[0]:''})"`:''}>${pad(i+1)}${list.length>1?'<sup>'+list.length+'</sup>':''}</span>`;}).join('')}</div><div class="iris-note">${series.slice(-12).map(s=>`<span style="color:${seriesColor(s)}">● ${LABEL[s.mode]} ${s.numbers.map(pad).join(' ')}</span>`).join('<br>')||'Активных комбинаций нет'}<br>Маленькое число — количество серий с этим числом.</div></section>`;}
function historyHtml(){return `<section class="iris-box"><h3>Последние тиражи</h3>${draws.slice(-10).reverse().map(d=>{const checks=data.series.flatMap(s=>s.results.filter(r=>r.draw===d.draw).map(r=>`${LABEL[s.mode]} ${r.hitCount}/${s.numbers.length}${r.payout>0?' 🔥':''}`));return `<details><summary>№${d.draw} · ${esc(d.time)} · ${checks.length} проверок</summary>${balls(d.balls)}<p class="iris-note">${checks.join(' · ')||'Зафиксированных серий на этот тираж нет'}</p></details>`;}).join('')}</section>`;}
function currentHtml(){const active=data.series.filter(s=>s.status==='active'),regular=active.filter(s=>s.mode==='IRIS'),mini=active.filter(s=>s.mode!=='IRIS');return `<div class="iris-layout"><div><h3>Текущие комбинации <span class="iris-pill">${active.length} серий</span></h3>${regular.map((s,i)=>seriesCard(s,i)).join('')||'<div class="iris-empty">Активных Iris пока нет. Новые серии появятся после свежего тиража при допуске A.</div>'}${mapHtml()}${historyHtml()}</div><aside><section class="iris-box"><h3>Как работает Iris</h3><ol><li>Проверяем допуск A.</li><li>Ищем независимые комбинации.</li><li>Фиксируем числа до факта.</li><li>Проверяем 5 тиражей отдельно.</li><li>Закрываем серию и сохраняем итог.</li></ol></section><section class="iris-box"><h3>Дополнительные режимы</h3>${['MINI3','MINI4'].map(m=>`<button class="iris-mode-button" data-iris-mini="${m}">${LABEL[m]} <span>${mini.filter(s=>s.mode===m).length} серий →</span></button>`).join('')}<p class="iris-note">Отдельный поиск, собственные серии и статистика.</p></section><section class="iris-box"><h3>Быстрые действия</h3><button data-iris-view="archive">Открыть архив</button><button data-iris-view="stats">Статистика</button><button data-iris-view="settings">Настройки и правила</button></section><p class="iris-note">Iris v0.1 — исследовательская версия отбора. Сервер продолжает учёт при закрытом телефоне, когда поступают новые факты.</p></aside></div>`;}
function archiveHtml(){if(filter==='all')return `<section class="iris-box"><h3>Архив Iris — выберите режим</h3><p class="iris-note">Серии и результаты каждого режима хранятся отдельно.</p>${E.MODES.map(m=>`<button data-iris-archive="${m}">${LABEL[m]} · ${data.series.filter(s=>s.mode===m).length} серий →</button>`).join('')}</section><button id="iris-export">Скачать весь архив JSON</button>`;const list=data.series.filter(s=>filter==='all'||s.mode===filter).sort((a,b)=>b.sourceCutoff-a.sourceCutoff||a.id.localeCompare(b.id));page=Math.min(page,Math.max(0,Math.ceil(list.length/10)-1));return `<section class="iris-box"><button data-iris-archive="all">← Выбрать режим</button><h3>Архив Iris · ${list.length} серий</h3><label>Режим<select id="iris-filter">${modeOptions}</select></label><div class="iris-note">Каждая серия содержит пять отдельных проверок. Прогнозные числа не меняются.</div></section>${list.slice(page*10,page*10+10).map((s,i)=>seriesCard(s,i,true)).join('')||'<div class="iris-empty">В этом режиме пока нет записей.</div>'}<div class="iris-pager"><button data-iris-page="-1" ${page===0?'disabled':''}>← Назад</button><span>${page+1} / ${Math.max(1,Math.ceil(list.length/10))}</span><button data-iris-page="1" ${(page+1)*10>=list.length?'disabled':''}>Далее →</button></div><button id="iris-export">Скачать архив JSON</button>`;}
function miniHtml(){const list=data.series.filter(s=>s.mode===filter&&s.status==='active');return `<h3>${LABEL[filter]} · самостоятельные серии</h3>${list.map((s,i)=>seriesCard(s,i)).join('')||'<div class="iris-empty">Нет активных серий этого режима.</div>'}<button data-iris-view="archive">Архив ${LABEL[filter]}</button>`;}
function statsHtml(){return `<label>Период<select id="iris-stats-limit"><option value="0">Полный архив</option><option value="20">Последние 20 серий</option><option value="50">Последние 50 серий</option></select></label><div class="iris-stat-grid">${E.MODES.map(m=>{const s=E.stats(data.series,m,statsLimit);return `<section class="iris-box"><h3>${LABEL[m]}</h3><div class="iris-stat-number">${s.series}<small>серий</small></div><p>${s.active} активных · ${s.closed} завершённых</p><p>Проверок: ${s.checks}<br>Среднее: ${s.average===null?'—':s.average.toFixed(2)} числа / тираж<br>Максимум совпадений: ${s.best??'—'}<br>🔥 Выплат: ${s.wins}<br>Известная сумма: ${money(s.knownPayout)}</p><p class="iris-note">${s.unknown?'Без расчёта суммы: '+s.unknown+' проверок.':''}<br>Распределение попаданий: ${Object.entries(s.distribution).map(([k,v])=>`${k}: ${v}`).join(' · ')||'—'}</p></section>`;}).join('')}</div><p class="iris-note">У основных Iris разная длина комбинаций. Среднее по ним описывает архив, а не вероятность выигрыша.</p>`;}
function settingsHtml(){return `<section class="iris-box"><h3>Настройки Iris · 0.1.0</h3><label class="iris-switch"><input id="iris-auto" type="checkbox" ${auto?'checked':''}> Автосоздание серий на этом устройстве</label><p class="iris-note">Серверный поиск работает отдельно. Переключатель не останавливает сервер или проверку уже записанных серий.</p><h3>Правила первой версии</h3><p>5 предыдущих тиражей → ритм числа → геометрические связи → отдельные комбинации → 5 будущих проверок.</p><p>A v0.1: пять последовательных свежих фактов, минимум пять чисел с ритмами 01010 / 11010 / 10101 / 10100 и геометрическая связь между ними.</p><p>Основной поиск: до четырёх комбинаций (7, 6, 8, 5 чисел), с ограничением сильного перекрытия. MINI‑3 и MINI‑4 ищутся отдельно при A.</p><p>B — PLAY+ пока не включён: точные условия ещё не восстановлены.</p><p class="iris-note">Это прозрачные временные правила v0.1, которые будем корректировать. Старые записи сохраняют свою версию. Таблица выплат используется из КЕНО 6.3; для 6–10 чисел сумма пока не определена.</p><h3>Сохранение</h3><p>Серверные серии сохраняются в общем архиве Iris. Созданные здесь дополнительные серии сохраняются на этом устройстве; выгрузка JSON доступна в архиве.</p></section>`;}
function render(){const opened=new Set([...host.querySelectorAll('details[open][data-iris-detail]')].map(x=>x.dataset.irisDetail)),e=data.evaluation||{},next=E.nextDraw(draws.at(-1)),active=data.series.filter(s=>s.status==='active');host.innerHTML=`<div class="iris-brand"><div><strong>◈ IRIS</strong><span>Комбинации · серии · проверка</span></div><small>КЕНО 6.3 · Iris 0.1.0</small></div><div class="iris-status-grid"><div class="iris-box"><small>Следующий тираж по базе</small><b>№${next?.draw||'—'}</b><span>${next?esc(next.date+' '+next.time)+' МСК':'Ждём историю'}</span></div><div class="iris-box"><small>Технический допуск A</small><b class="${e.permissionA?'iris-green':'iris-amber'}">${e.permissionA?'● ЕСТЬ':'○ НЕТ'}</b><span>${esc(e.message||'Проверяем данные…')}</span></div><div class="iris-box"><small>Текущие серии</small><b>${active.length}</b><span>Iris ${active.filter(s=>s.mode==='IRIS').length} · MINI‑3 ${active.filter(s=>s.mode==='MINI3').length} · MINI‑4 ${active.filter(s=>s.mode==='MINI4').length}</span></div></div><div class="iris-actions"><button id="iris-generate" class="iris-primary" ${busy||!db?'disabled':''}>${busy?'Обновление…':'↻ Рассчитать новые комбинации'}</button><button id="iris-check" ${busy?'disabled':''}>Проверить и сохранить</button></div><p class="iris-save" role="status">${esc(message)}</p><nav class="iris-tabs">${[['current','Комбинации'],['map','Карта 1–80'],['history','Тиражи'],['archive','Архив Iris'],['stats','Статистика']].map(([id,label])=>`<button data-iris-view="${id}" class="${view===id?'selected':''}">${label}</button>`).join('')}</nav><div class="iris-content">${view==='current'?currentHtml():view==='map'?mapHtml():view==='history'?historyHtml():view==='archive'?archiveHtml():view==='stats'?statsHtml():view==='mini'?miniHtml():settingsHtml()}</div>`;for(const el of host.querySelectorAll('details[data-iris-detail]'))if(opened.has(el.dataset.irisDetail))el.open=true;const f=host.querySelector('#iris-filter');if(f)f.value=filter;const sl=host.querySelector('#iris-stats-limit');if(sl)sl.value=statsLimit;}
host.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.irisView){view=b.dataset.irisView;page=0;render();}if(b.dataset.irisArchive){filter=b.dataset.irisArchive;view='archive';page=0;render();}if(b.dataset.irisMini){filter=b.dataset.irisMini;view='mini';render();}if(b.dataset.irisPage){page+=Number(b.dataset.irisPage);render();}if(b.id==='iris-check')refresh(false);if(b.id==='iris-generate')refresh(true);if(b.id==='iris-export'){const blob=new Blob([JSON.stringify({version:E.VERSION,exportedAt:new Date().toISOString(),series:data.series},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='IRIS-v63-archive.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
host.addEventListener('change',event=>{const el=event.target;if(el.id==='iris-filter'){filter=el.value;page=0;render();}if(el.id==='iris-map-scope'){scope=el.value;render();}if(el.id==='iris-stats-limit'){statsLimit=Number(el.value);render();}if(el.id==='iris-auto'){auto=el.checked;try{localStorage.setItem('iris-v63-auto',String(auto));}catch{message='Не удалось сохранить настройку';}render();}});
window.addEventListener('online',()=>refresh(auto));document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh(auto);});
async function start(){render();try{db=await openDb();const saved=await cached();if(saved){data=saved;draws=saved.draws||[];message='Сохранённый архив · проверяю обновления';render();}}catch(e){message='Локальная запись недоступна: '+e.message;}await refresh(auto);setInterval(()=>{if(!document.hidden)refresh(auto);},60000);}
start();
})();
